# Generated by Django 3.1.6 on 2021-03-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='digital',
        ),
    ]
