# Generated by Django 3.1.7 on 2021-07-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('wasser', 'Wasser'), ('wein', 'Wein'), ('bier', 'Bier'), ('likor', 'Likor'), ('softdrinks', 'Softdrinks'), ('energydrink', 'Energydrink')], default='wasser', max_length=200),
        ),
    ]
